# -*- coding: utf-8 -*-
import csv
from pyrevit import revit, forms, DB

#   This is a pyrevit script to import the extracted room labels

# 1. UI: Pick the CSV file generated by the PDF extractor
csv_file = forms.pick_file(file_ext='csv', title="Select Room Label CSV")

if csv_file:
    # 2. Get active document and view details
    doc = revit.doc
    active_view = doc.ActiveView
    active_level = active_view.GenLevel
    
    if not active_level:
        forms.alert("Please run this script in a Floor Plan view with an associated level.", exitscript=True)

    # 3. Find the "Room Names" Text Note Type
    text_types = DB.FilteredElementCollector(doc).OfClass(DB.TextNoteType).ToElements()
    target_type = next((t for t in text_types if t.get_Parameter(DB.BuiltInParameter.SYMBOL_NAME_PARAM).AsString() == "Room Names"), None)
    
    if not target_type:
        forms.alert("Could not find Text Note Type: 'Room Names'. Please create it in your project first.", exitscript=True)
    
    # 4. UI: Pick reference point in Revit (e.g. Grid 1)
    try:
        origin_point = revit.pick_point("Select the location of Grid 1 (Anchor A) in Revit")
    except Exception:
        forms.alert("Point selection cancelled.", exitscript=True)

    # 5. Transaction to create elements
    with revit.Transaction("Create Labels from PDF Data"):
        success_count = 0
        error_count = 0
        
        with open(csv_file, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                try:
                    # Read scale factor from the CSV row
                    scale_factor = float(row['Scale_Factor'])
                    
                    # Extract and calibrate coordinates
                    # Logic: Origin + (Relative Coord * Scale Factor)
                    x = origin_point.X + (float(row['X_Relative']) * scale_factor)
                    y = origin_point.Y + (float(row['Y_Relative']) * scale_factor)
                    z = origin_point.Z
                    
                    # Create the XYZ point for Text placement
                    point = DB.XYZ(x, y, z)
                    
                    # 6. Create the Text Note
                    # Options can be adjusted if needed (e.g. alignment)
                    new_text = DB.TextNote.Create(doc, active_view.Id, point, row['Room_Name'], target_type.Id)
                    
                    if new_text:
                        print("CREATED: {} at ({:.2f}, {:.2f})".format(row['Room_Name'], x, y))
                        success_count += 1
                    else:
                        error_count += 1
                except Exception as e:
                    print("ERROR: Row {}: {}".format(row.get('Room_Name', 'Unknown'), e))
                    error_count += 1

        
        forms.alert("Import Complete!\n\nSuccess: {}\nFailed: {}".format(success_count, error_count), title="Room Label Import")

