# -*- coding: utf-8 -*-
import csv
from pyrevit import revit, forms, DB

#   This script imports objects (vents/grills/controllers) based on exported PDF label CSV data.
#   It places them 30cm below the label and at the detected ceiling height.

# 1. UI: Pick the CSV file generated by the PDF extractor
csv_file = forms.pick_file(file_ext='csv', title="Select Room Label CSV")

if csv_file:
    doc = revit.doc
    active_view = doc.ActiveView
    active_level = active_view.GenLevel
    
    if not active_level:
        forms.alert("Please run this script in a Floor Plan view with an associated level.", exitscript=True)

    # 2. Read CSV data
    csv_rows = []
    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            csv_rows.append(row)
    
    if not csv_rows:
        forms.alert("The CSV file is empty.", exitscript=True)

    # 3. UI: Select Room Names from CSV
    # Get unique room names from the CSV rows
    unique_room_names = sorted(list(set(row.get('Room_Name', 'Unknown') for row in csv_rows)))
    
    selected_room_names = forms.SelectFromList.show(
        unique_room_names,
        title="Select Room Names (Objects will be placed in ALL matching rooms)",
        multiselect=True,
        search_ber=True
    )
    
    if not selected_room_names:
        forms.alert("No room names selected. Exiting.", exitscript=True)
    
    # Filter all rows that match the selected room names
    selected_rows = [row for row in csv_rows if row.get('Room_Name') in selected_room_names]

    # 4. UI: Select the Family Type to place
    all_symbols = DB.FilteredElementCollector(doc).OfClass(DB.FamilySymbol).ToElements()
    
    # Create a searchable list: "Family Name: Type Name"
    # We filter out symbols that are not valid for placement to keep the list clean
    symbol_dict = {}
    for s in all_symbols:
        try:
            name = "{}: {}".format(s.Family.Name, s.get_Parameter(DB.BuiltInParameter.SYMBOL_NAME_PARAM).AsString())
            symbol_dict[name] = s
        except:
            continue
    
    selected_symbol_key = forms.SelectFromList.show(
        sorted(symbol_dict.keys()), 
        title="Select Object to Place", 
        multiselect=False,
        search_ber=True
    )
    
    if not selected_symbol_key:
        forms.alert("No object selected. Exiting.", exitscript=True)
    
    target_symbol = symbol_dict[selected_symbol_key]

    # 5. UI: Pick reference point in Revit (Grid 1 Anchor)
    try:
        origin_point = revit.pick_point("Select the location of Grid 1 (Anchor A) in Revit")
    except Exception:
        forms.alert("Point selection cancelled.", exitscript=True)

    # 6. Process Selection and Place Objects
    with revit.Transaction("Place Objects for Selected Rooms"):
        if not target_symbol.IsActive:
            target_symbol.Activate()
            doc.Regenerate()

        success_count = 0
        error_count = 0
        
        # Constants
        OFFSET_Y_FT = 30.0 / 30.48 # 30cm offset
        FIXED_HEIGHT_FT = 2400.0 / 304.8 # 2400mm fixed height
        
        for row in selected_rows:
            try:
                room_name = row.get('Room_Name', 'Unknown')
                scale_factor = float(row['Scale_Factor'])
                
                # Calculate Revit coordinates
                x = origin_point.X + (float(row['X_Relative']) * scale_factor)
                y = origin_point.Y + (float(row['Y_Relative']) * scale_factor)
                
                # Apply the 30cm offset (downwards in Y)
                y_target = y - OFFSET_Y_FT
                
                # Calculate elevation (Fixed 2400mm above level)
                placement_z = active_level.Elevation + FIXED_HEIGHT_FT
                placement_point = DB.XYZ(x, y_target, placement_z)
                
                # Place the instance
                new_inst = doc.Create.NewFamilyInstance(
                    placement_point, 
                    target_symbol, 
                    active_level, 
                    DB.Structure.StructuralType.NonStructural
                )
                
                if new_inst:
                    success_count += 1
                    
            except Exception as e:
                print("ERROR: Row {}: {}".format(row.get('Room_Name', 'Unknown'), e))
                error_count += 1

    # 7. Final Report
    forms.alert(
        "Placement Complete!\n\nSuccess: {}\nErrors: {}".format(success_count, error_count), 
        title="Process Summary"
    )
